spring:
  datasource:
    url: jdbc:mysql://localhost:3306/contosouniversitydata
    username: root
    password: Q25rw4e3
  jpa:
    hibernate:
      ddl-auto: update
    generate-ddl: true
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL8Dialect

server:
  port: 8081
  address: localhost

logging.level.org.hibernate:
  SQL: DEBUG
  type:
    descriptor:
      sql:
        BasicBinder: TRACE